wye/organisations/urls.py
from django.conf.urls import url
from .views import (
    OrganisationCreate, OrganisationDetail,
    OrganisationUpdate, OrganisationList,
    OrganisationDeactive, OrganisationMemberAdd)

urlpatterns = [
    url(r'^create/$', OrganisationCreate.as_view(),
        name="organisation_create"),
    url(r'^(?P<pk>[0-9]+)/(?P<action>active|deactive)/$',
        OrganisationDeactive.as_view(), name="organisation_delete"),
    url(r'^(?P<pk>[0-9]+)/edit/$',
        OrganisationUpdate.as_view(), name="organisation_update"),
    url(r'^(?P<pk>[0-9]+)/member-add/$',
        OrganisationMemberAdd.as_view(), name="organisation_member_add"),
    url(r'^(?P<pk>[0-9]+)/$', OrganisationDetail.as_view(),
        name="organisation_details"),
    url(r'^$', OrganisationList.as_view(), name="organisation_list"),

]

wye/profiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^dashboard$', views.UserDashboard.as_view(),
        name="dashboard"),
    url(r'^(?P<slug>[a-zA-Z0-9@._-]+)/$',
        views.profile_view, name='profile-page'),
    url(r'^(?P<slug>[a-zA-Z0-9@._-]+)/edit/$',
        views.ProfileEditView.as_view(), name='profile-edit'),
    url(r'^(?P<slug>[a-zA-Z0-9@._-]+)/deactivate/$',
        views.account_deactivate, name='account_deactivate')
]

wye/regions/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^lead/create/$', views.RegionalLeadCreateView.as_view(),
        name="lead-create"),
    url(r'^lead/(?P<pk>[0-9]+)/edit/$', views.RegionalLeadUpdateView.as_view(),
        name="lead-update"),
    url(r'^lead/get_leads/(?P<l_id>\w+)/$', views.RegionalLeadCreateView().get_leads, name='get_leads'),
    url(r'^state/create/$', views.StateCreateView.as_view(),
        name="state-create"),
    url(r'^state/(?P<pk>[0-9]+)/edit/$', views.StateEditView.as_view(),
        name="state-update"),

    url(r'^location/create/$', views.LocationCreateView.as_view(),
        name="location-create"),
    url(r'^location/(?P<pk>[0-9]+)/edit/$', views.LocationUpdateView.as_view(),
        name="location-update"),
    url(r'^$', views.RegionalListView.as_view(), name="regions-home-page")

]

wye/reports/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^export_workshops/$', views.get_tutor_college_poc_csv,
        name="workshop-csv"),
    url(r'^export_users/$', views.get_all_user_info,
        name="workshop-csv"),
    url(r'^$', views.index, name="home"),

]

wye/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import TemplateView

from wye.base.views import HomePageView
from wye.profiles.views import (
    UserDashboard,
    contact,
    partner_view,
    account_redirect)
from wye.organisations.views import activate_view
from wye.workshops.views import upcoming_workshops

urlpatterns = [
    url(r'^account_redirect/$', account_redirect, name='account-redirect'),
    url(r'^accounts/', include('allauth.urls')),


    url(r'^django-admin/', include(admin.site.urls)),
    url(r'^dashboard/$', UserDashboard.as_view(),
        name="dashboard"),
    url(r'^about/$', TemplateView.as_view(template_name='about.html',),
        name='about'),
    url(r'^contact/$', contact,
        name='contact'),
    url(r'^partner/$', partner_view,
        name='partner'),
    url(r'^supporter/$', TemplateView.as_view(template_name='supporters.html',),
        name='supporter'),
    url(r'^thankyou/$', TemplateView.as_view(template_name='contact.html'),
        name='thankyou'),
    url(r'^workshops_info/$', TemplateView.as_view(
        template_name='workshops_info.html',),
        name='workshops_info'),
    url(r'^workshops_upcoming/$',
        upcoming_workshops, name="upcoming_workshops"),
    url(r'^faq/$', TemplateView.as_view(template_name='faq.html',),
        name='faq'),
    url(r'^organisation/',
        include('wye.organisations.urls', namespace="organisations")),
    url(r'^workshop/',
        include('wye.workshops.urls', namespace="workshops")),
    url(r'^profile/',
        include('wye.profiles.urls', namespace="profiles")),
    url(r'^region/',
        include('wye.regions.urls', namespace="regions")),
    url(r'^reports/',
        include('wye.reports.urls', namespace="reports")),
    url(r'^invitation/(?P<user_id>[0-9]+)-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
        view=activate_view, name="invitation_register"),
    url(r'^$', HomePageView.as_view(),
        name='home-page'),
] + static(
    settings.STATIC_URL,
    document_root=settings.STATICFILES_DIRS) + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

wye/organisations/models.py
from django.contrib.auth.models import User
from django.db import models

from wye.base.constants import OrganisationType
from wye.base.models import AuditModel
from wye.regions.models import Location


class Organisation(AuditModel):
    organisation_type = models.PositiveSmallIntegerField(
        choices=OrganisationType.CHOICES, verbose_name="organisation type")
    name = models.CharField(max_length=300, unique=True)
    description = models.TextField()
    full_address = models.TextField(blank=True, null=True)
    location = models.ForeignKey(Location)
    pincode = models.CharField(max_length=6, blank=True, null=True)
    address_map_url = models.URLField(blank=True, null=True)
    organisation_role = models.CharField(
        max_length=300, verbose_name="Your position in organisation")
    user = models.ManyToManyField(User, related_name='organisation_users')
    active = models.BooleanField(default=True)

    @classmethod
    def list_user_organisations(cls, user):
        return cls.objects.filter(user=user, active=True)

    @property
    def get_organisation_user_list(self):
        return self.user.all()

    def toggle_active(self, logged_user, **kwargs):
        """
        Helper method to toggle active flag for the model.
        """

        action_map = {'active': True, 'deactive': False}
        action = kwargs.get('action')
        # check if user is only poc for the organisation
        self.user.remove(logged_user)
        if not self.user.count():
            # if there are no more poc for this organisation disable it
            # else Organisation will be active
            self.active = action_map.get(action)
            self.save()

        return {
            'status': True,
            'msg': 'Organisation disabled'}

    class Meta:
        db_table = 'organisations'

    def __str__(self):
        return '{} , {}'.format(self.name, self.location)

wye/reports/models.py
# from django.db import models

# Create your models here.

wye/base/views.py
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect
from wye.organisations.models import Organisation
from wye.profiles.models import Profile
from wye.workshops.models import Workshop

from .constants import WorkshopStatus


class HomePageView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        organisationObj = Organisation.objects.filter(active=True)
        workshopObj = Workshop.objects.filter(is_active=True)
        context['organisation_registered_count'] = organisationObj.count()
        context['completed_workshop_count'] = workshopObj.filter(
            status=WorkshopStatus.COMPLETED).count()
        workshopObj = workshopObj.filter(status__in=[
            WorkshopStatus.REQUESTED,
            WorkshopStatus.ACCEPTED,
            WorkshopStatus.DECLINED])
        workshop_list = Workshop.objects.filter(
            is_active=True
        ).filter(
            status__in=[WorkshopStatus.REQUESTED, WorkshopStatus.ACCEPTED]
        ).order_by('expected_date')
        context['requested_workshop_count'] = workshopObj.count()
        context['tutor_registered_count'] = Profile.objects.filter(
            usertype__slug="tutor").count()
        context['upcoming_workshops'] = workshop_list
        return context


def verify_user_profile(f):
    '''
    This decorator check  whether the user are valid for certain views
    '''
    def wrap(request, *args, **kwargs):
        user_profile, created = Profile.objects.get_or_create(
            user__id=request.user.id)
        if not user_profile.is_profile_filled:
            return HttpResponseRedirect(
                '/profile/{}/edit'.format(request.user.username))
        return f(request, *args, **kwargs)
    return wrap

wye/regions/views.py
import json
from braces import views
from django.http.response import HttpResponse
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.views import generic

from wye.profiles.models import Profile
from . import forms, models


class RegionalListView(views.StaffuserRequiredMixin, generic.ListView):
    model = models.RegionalLead
    template_name = 'regions/index.html'

    def get_context_data(self, *args, **kwargs):
        context = super(
            RegionalListView, self).get_context_data(*args, **kwargs)
        context['state_list'] = models.State.objects.all()
        context['location_list'] = models.Location.objects.all()
        context['regional_list'] = models.RegionalLead.objects.all()
        context['user'] = self.request.user
        return context


class StateCreateView(views.StaffuserRequiredMixin, generic.CreateView):
    model = models.State
    form_class = forms.StateForm
    success_url = '/region/'
    template_name = 'regions/state/create.html'

    def post(self, request, *args, **kwargs):
        form = forms.StateForm(data=request.POST)
        if form.is_valid():
            form.modified_by = request.user
            form.created_by = request.user
            form.instance.save()
            return HttpResponseRedirect(self.success_url)
        else:
            return render(request, self.template_name, {'form': form})


class StateEditView(views.StaffuserRequiredMixin, generic.UpdateView):
    model = models.State
    form_class = forms.StateForm
    success_url = '/region/'
    template_name = 'regions/state/edit.html'


class LocationCreateView(views.StaffuserRequiredMixin, generic.CreateView):
    model = models.Location
    form_class = forms.LocationForm
    success_url = '/region/'
    template_name = 'regions/location/create.html'

    def post(self, request, *args, **kwargs):
        form = forms.LocationForm(data=request.POST)
        if form.is_valid():
            form.modified_by = request.user
            form.created_by = request.user
            form.instance.save()
            return HttpResponseRedirect(self.success_url)
        else:
            return render(request, self.template_name, {'form': form})


class LocationUpdateView(views.StaffuserRequiredMixin, generic.UpdateView):
    model = models.Location
    form_class = forms.LocationForm
    success_url = '/region/'
    template_name = 'regions/location/edit.html'


class RegionalLeadCreateView(views.StaffuserRequiredMixin, generic.CreateView):
    model = models.RegionalLead
    form_class = forms.RegionalLeadForm
    success_url = '/region/'
    template_name = 'regions/lead/create.html'

    def get_leads(self, request, l_id):
        lead_choices = Profile.objects.filter(
            location=l_id
        ).values_list('user__id', 'user__username')
        return HttpResponse(json.dumps(list(lead_choices)))

    def post(self, request, *args, **kwargs):
        if request.method == 'POST' and request.is_ajax:
                form = forms.RegionalLeadForm(data=request.POST)
                lead_choices = request.POST.get('leads')
                form.fields['leads'].choices = (lead_choices, lead_choices)

                if form.is_valid():
                    form.modified_by = request.user
                    form.created_by = request.user
                    form.save()
                    return HttpResponseRedirect(self.success_url)
                else:
                    return render(request, self.template_name, {'form': form})


class RegionalLeadUpdateView(views.StaffuserRequiredMixin, generic.UpdateView):
    model = models.RegionalLead
    form_class = forms.RegionalLeadForm
    success_url = '/region/'
    template_name = 'regions/lead/edit.html'

wye/reports/views.py
import datetime
import csv
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.models import User
from wye.base.constants import WorkshopStatus
from wye.workshops.models import Workshop
from wye.profiles.models import Profile


@login_required
def index(request):
    context_dict = {}
    if not request.user.is_staff:
        template_name = '403.html'
        return render(request, template_name, context_dict)

    workshops = Workshop.objects.filter(is_active=True)
    context_dict['workshops'] = {
        'completed': workshops.filter(status=WorkshopStatus.COMPLETED).count(),
        'drafted': workshops.filter(status=WorkshopStatus.DRAFT).count(),
        'hold': workshops.filter(status=WorkshopStatus.HOLD).count(),
        'feedback_pending': workshops.filter(
            status=WorkshopStatus.FEEDBACK_PENDING).count(),
    }
    workshop_finished = workshops.filter(
        status__in=[WorkshopStatus.COMPLETED,
                    WorkshopStatus.FEEDBACK_PENDING])
    tutors_dict = {}
    tutors = [
        user for w in workshop_finished for user in w.presenter.all()]
    for tutor in tutors:
        tutors_dict[tutor.id] = [
            tutor.username,
            tutor.first_name,
            tutor.last_name,
            tutor.profile.get_workshop_completed_count]
    context_dict['tutors'] = tutors_dict
    org_dict = {}
    orgs = [
        w.requester for w in workshop_finished]
    for org in orgs:
        if org.id in org_dict:
            count = org_dict[org.id][1] + 1
        else:
            count = 1
        org_dict[org.id] = [org.name, count, org.location.name]

    context_dict['orgs'] = org_dict
    template_name = 'reports/index.html'
    years = [('all', 'All')]
    for y in range(2016, int(datetime.datetime.today().strftime('%Y')) + 1):
        years.append((y, y))
    context_dict['years'] = years
    return render(request, template_name, context_dict)


@login_required
def get_tutor_college_poc_csv(request):
    # if not request.user.is_staff:
    #     template_name = '403.html'
    #     return render(request, template_name, {})
    usertype = request.POST['usertype']
    year = request.POST['years']
    workshops = Workshop.objects.filter(is_active=True)
    if year != 'all':
        workshops = workshops.filter(expected_date__year=year)

    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="workshops.csv"'
    writer = csv.writer(response)
    csv_titles = ['Worshop Id', 'Workshop Date', 'Location', 'College']
    if usertype == 'tutor':
        csv_titles.extend(['Presenter Name', 'Presenter Email'])
    elif usertype == 'poc':
        csv_titles.extend(['College POC Name', 'College POC Email'])
    else:
        csv_titles.extend(['Presenter Name', 'Presenter Email'])
        csv_titles.extend(['College POC Name', 'College POC Email'])
    writer.writerow(csv_titles)

    for obj in workshops:
        row = [
            obj.id, obj.expected_date,
            obj.location.name, obj.requester.name]
        if usertype == 'tutor':
            for u in obj.presenter.all():
                row.append("{} {}".format(u.first_name, u.last_name))
                row.append("{}".format(u.email))
        elif usertype == 'poc':
            for u in obj.requester.user.all():
                row.append("{} {}".format(u.first_name, u.last_name))
                row.append("{}".format(u.email))
        else:
            for u in obj.presenter.all():
                row.append("{} {}".format(u.first_name, u.last_name))
                row.append("{}".format(u.email))
            for u in obj.requester.user.all():
                row.append("{} {}".format(u.first_name, u.last_name))
                row.append("{}".format(u.email))
        writer.writerow(row)
    return response


@login_required
def get_all_user_info(request):
    users = User.objects.all()
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="all_users.csv"'
    writer = csv.writer(response)
    csv_titles = [
        'User Id', 'First Name', 'Last Name', 'Email', 'Is Active',
        'Is Presenter', 'Is POC', 'Is Regional Lead', 'Is Organiser']
    writer.writerow(csv_titles)
    for obj in users:
        try:
            row = [
                obj.id,
                obj.first_name,
                obj.last_name,
                obj.email,
                obj.is_active,
                Profile.is_presenter(obj),
                Profile.is_coordinator(obj),
                Profile.is_regional_lead(obj),
                Profile.is_organiser(obj)]

            writer.writerow(row)
        except Exception:
            pass
    return response

wye/templates/organisation/create.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% include 'autocomplete_light/static.html' %}
{% block title %}Organisation | {{ block.super }}{% endblock %}

{% block header %}
    <div class="banner push-2 text-center">
        <h1 class="space-0">Create Organisation</h1>
    </div>
{% endblock %}

{% block content %}
    <div class="push-6-bottom">
        <div class="row push-2-bottom">
            <div class="col-sm-12 sub">
                <a href="{% url 'organisations:organisation_list' %}"><i class="fa fa-arrow-left"></i>&nbsp;&nbsp;My Organisations</a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2">
                <form method="post" action="{% url 'organisations:organisation_create' %}">{% csrf_token %}
                    {{form.as_p}}
                    <input type="submit" class="btn btn-theme regular" value="Create">
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block footer_scripts %}
  <script src="{% static 'autocomplete.js' %}"></script>
{% endblock %}

wye/templates/organisation/detail.html
{% extends "base.html" %}
{% block title %}Organisation | {{ block.super }}{% endblock %}
{% block header %}
    <div class="banner push-2 text-center">
        <h1 class="space-0">Organisations</h1>
    </div>
{% endblock %}

{% block content %}
    <div class="push-4-bottom">
        <div class="row push-1-bottom">
            <div class="col-xs-6 sub">
                <a href="{% url 'organisations:organisation_list' %}"><i class="fa fa-arrow-left"></i>&nbsp;&nbsp;My Organisations</a>
            </div>
            {% if object.created_by == request.user %}
            <div class="col-xs-6 text-right">
                <a href="{% url 'organisations:organisation_update' organisation.pk  %}" class="btn btn-theme-primary sub pad-1"><i class="fa fa-cog"></i>Edit</a>

                <a href="javascript:void(0);" data-url="{% url 'organisations:organisation_delete' organisation.pk 'deactive' %}" class="btn btn-danger sub pad-1 org-delete">
                <i class="fa fa-times"></i>Delete</a>
            </div>
            {% endif %}
        </div>

        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-heading regular bold">
                        {{object.name}}
                    </div>
                    <ul class="list-group sub">
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-xs-4"><strong>Organisation Type</strong></div>
                                <div class="col-xs-8">{{object.get_organisation_type_display}}</div>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-xs-4"><strong>Description</strong></div>
                                <div class="col-xs-8">{{object.description}}</div>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-xs-4"><strong>Full Address</strong></div>
                                <div class="col-xs-8">{{object.full_address}}</div>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-xs-4"><strong>Location</strong></div>
                                <div class="col-xs-8">{{object.location}}</div>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-xs-4"><strong>Pincode</strong></div>
                                <div class="col-xs-8">{{object.pincode}}</div>
                            </div>
                        </li>
                        {% if object.full_address and GOOGLE_MAP_API %}
                        <li class="list-group-item">
                          <div class="row">
                              <div class="col-xs-4"><strong>Address Map</strong></div>
                              <div class="col-xs-8">
                                <iframe width="600" height="450" frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?q=place:{{ object.full_address }}&key={{ GOOGLE_MAP_API }}" allowfullscreen>
                                </iframe>
                              </div>
                          </div>
                        </li>
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-xs-4"><strong>Address Map Url</strong></div>
                                <div class="col-xs-8"><a href="{{object.address_map_url}}" target="_blank">{{object.address_map_url}}</a></div>
                            </div>
                        </li>
                        {% endif %}
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-xs-4"><strong>Active</strong></div>
                                <div class="col-xs-8">{{object.active}}</div>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-xs-4"><strong>Users</strong></div>
                                <div class="col-xs-8">
                                    <ul class="list-silent">
                                        {% for u in object.user.all %}
                                            <li>{{u.first_name}} {{u.last_name}}  |  {{u.email}}</li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div><br>
                            {% if object.created_by == request.user %}
                            <a href="{% url 'organisations:organisation_member_add' organisation.pk  %}" class="btn btn-success"><i class="fa fa-cog"></i>Add Users</a>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block footer_scripts %}
    <script>
        'use strict';
        $(function(){
            $('.clickable-row td:nth-child(-n + 5)').click(function() {
               window.document.location = $(this).parent().attr('data-href');
            });

        $(".org-delete").bind('click', function() {
            $.post($(this).attr('data-url'), {}, function(data) {
                if (data["status"]) {
                	window.location = '/organisation/';
                }
            });
        });
    });
    </script>
{% endblock %}

wye/templates/organisation/edit.html
{% extends "base.html" %}
{% block title %}Organisation | {{ block.super }}{% endblock %}
{% block header %}
    <div class="banner push-2 text-center">
        <h1 class="space-0">Organisations</h1>
    </div>
{% endblock %}

{% block content %}
    <div class="push-4-bottom">
        <div class="row push-2-bottom">
            <div class="col-xs-6 sub">
                <a href="{% url 'organisations:organisation_list' %}"><i class="fa fa-arrow-left"></i>&nbsp;&nbsp;My Organisations</a>
            </div>
            <div class="col-xs-6 text-right">
                <a href="{% url 'organisations:organisation_details' organisation.pk %}" class="btn btn-theme-primary sub pad-1"><i class="fa fa-eye"></i>&nbsp;&nbsp;View<span class="hidden-xs"> Organisation</span></a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2">
                <form method="post" action="">{% csrf_token %}
                    {{form.as_p}}
                    <input type="submit" class="btn btn-theme sub" value="Update">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

wye/templates/organisation/list.html
{% extends "base.html" %}
{% block title %}Organisation | {{ block.super }}{% endblock %}
{% block header %}
    <div class="banner push-2 text-center">
        <h1 class="space-0">Organisations</h1>
    </div>
{% endblock %}

{% block content %}
	<section class="myorganisations">
		<div class="push-4-bottom">
			<div class="row">
				<div class="col-xs-6">
					<h3 class="space-1q-top">My Organisations</h3>
				</div>

				<div class="col-xs-6 text-right">
					<a href="{% url 'organisations:organisation_create' %}" class="btn btn-theme-primary sub pad-1"><i class="fa fa-plus"></i>&nbsp;&nbsp;<span class="hidden-xs">Add Organisation</span></a>
				</div>

			</div>
			<div class="row push-1">
				<div class="col-sm-12">
					{% if not org_created_list %}
						<p class="gray sub"><em>You have not created organisations.</em></p>
					{% else %}
						<div class="table-responsive">
							<table class="table table-bordered table-clickable sub">
								<thead>
									<tr>
										<th>Name</th>
										<th>Location</th>
										<th>Type</th>
									</tr>
								</thead>
								<tbody>
									{% for org in org_created_list %}
									{% if is_not_tutor %}
										<tr class="clickable-row" data-href="{% url 'organisations:organisation_details' org.pk %}">
									{% else %}
										<tr>
									{% endif %}
											<td>{{org.name }}</td>
											<td>{{org.location}}</td>
											<td>{{org.get_organisation_type_display}}</td>
										</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					{% endif %}
				</div>
			</div>
		</div>
	</section>
	{% if org_belongs_list %}
		<section class="organisations_working_for">
			<div class="push-4-bottom push-1-top">
				<h3>Other organisations I am member of</h3>
				<div class="row">
					<div class="col-sm-12">
						<div class="table-responsive">
							<table class="table table-bordered table-clickable sub">
								<thead>
									<tr>
										<th>Name</th>
										<th>Location</th>
										<th>Type</th>
									</tr>
								</thead>
								<tbody>
									{% for org in org_belongs_list %}
										<tr class="clickable-row" data-href="{% url 'organisations:organisation_details' org.pk %}">
											<td>{{org.name }}</td>
											<td>{{org.location}}</td>
											<td>{{org.get_organisation_type_display}}</td>
										</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</section>
	{% endif %}
	{% if regional_org_list %}
		<section class="organisations_working_for">
			<div class="push-4-bottom push-1-top">
				<h3>Regional Organisations</h3>
				<div class="row">
					<div class="col-sm-12">
						<div class="table-responsive">
							<table class="table table-bordered table-clickable sub">
								<thead>
									<tr>
										<th>Name</th>
										<th>Location</th>
										<th>Type</th>
									</tr>
								</thead>
								<tbody>
									{% for org in regional_org_list %}
										<tr class="clickable-row" data-href="{% url 'organisations:organisation_details' org.pk %}">
											<td>{{org.name }}</td>
											<td>{{org.location}}</td>
											<td>{{org.get_organisation_type_display}}</td>
										</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</section>
	{% endif %}
{% endblock %}
{% block footer_scripts %}
    <script>
        'use strict';
        $(function(){
            $('.clickable-row').click(function() {
                window.document.location = $(this).data('href');
            });
        });
    </script>
{% endblock %}

wye/templates/organisation/member-add.html
{% extends "base.html" %}
{% block title %}Organisation | {{ block.super }}{% endblock %}
{% block header %}
    <div class="banner push-2 text-center">
        <h1 class="space-0">Organisations</h1>
    </div>
{% endblock %}

{% block content %}
    <div class="push-4-bottom">
        <div class="row push-2-bottom">
            <div class="col-xs-6 sub">
                <a href="{% url 'organisations:organisation_list' %}"><i class="fa fa-arrow-left"></i>&nbsp;&nbsp;My Organisations</a>
            </div>
            <div class="col-xs-6 text-right">
                <a href="{% url 'organisations:organisation_details' organisation.pk %}" class="btn btn-theme-primary sub pad-1"><i class="fa fa-eye"></i>&nbsp;&nbsp;View<span class="hidden-xs"> Organisation</span></a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2">
                <form method="post" action="">{% csrf_token %}
                    {{form.as_p}}
                    <input type="submit" class="btn btn-theme sub" value="Update">
                </form>
            </div>
        </div>
    </div>
{% endblock %}