wye/profiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^dashboard$', views.UserDashboard.as_view(),
        name="dashboard"),
    url(r'^(?P<slug>[a-zA-Z0-9@._-]+)/$',
        views.profile_view, name='profile-page'),
    url(r'^(?P<slug>[a-zA-Z0-9@._-]+)/edit/$',
        views.ProfileEditView.as_view(), name='profile-edit'),
    url(r'^(?P<slug>[a-zA-Z0-9@._-]+)/deactivate/$',
        views.account_deactivate, name='account_deactivate')
]

wye/regions/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^lead/create/$', views.RegionalLeadCreateView.as_view(),
        name="lead-create"),
    url(r'^lead/(?P<pk>[0-9]+)/edit/$', views.RegionalLeadUpdateView.as_view(),
        name="lead-update"),
    url(r'^lead/get_leads/(?P<l_id>\w+)/$', views.RegionalLeadCreateView().get_leads, name='get_leads'),
    url(r'^state/create/$', views.StateCreateView.as_view(),
        name="state-create"),
    url(r'^state/(?P<pk>[0-9]+)/edit/$', views.StateEditView.as_view(),
        name="state-update"),

    url(r'^location/create/$', views.LocationCreateView.as_view(),
        name="location-create"),
    url(r'^location/(?P<pk>[0-9]+)/edit/$', views.LocationUpdateView.as_view(),
        name="location-update"),
    url(r'^$', views.RegionalListView.as_view(), name="regions-home-page")

]

wye/reports/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^export_workshops/$', views.get_tutor_college_poc_csv,
        name="workshop-csv"),
    url(r'^export_users/$', views.get_all_user_info,
        name="workshop-csv"),
    url(r'^$', views.index, name="home"),

]

wye/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import TemplateView

from wye.base.views import HomePageView
from wye.profiles.views import (
    UserDashboard,
    contact,
    partner_view,
    account_redirect)
from wye.organisations.views import activate_view
from wye.workshops.views import upcoming_workshops

urlpatterns = [
    url(r'^account_redirect/$', account_redirect, name='account-redirect'),
    url(r'^accounts/', include('allauth.urls')),


    url(r'^django-admin/', include(admin.site.urls)),
    url(r'^dashboard/$', UserDashboard.as_view(),
        name="dashboard"),
    url(r'^about/$', TemplateView.as_view(template_name='about.html',),
        name='about'),
    url(r'^contact/$', contact,
        name='contact'),
    url(r'^partner/$', partner_view,
        name='partner'),
    url(r'^supporter/$', TemplateView.as_view(template_name='supporters.html',),
        name='supporter'),
    url(r'^thankyou/$', TemplateView.as_view(template_name='contact.html'),
        name='thankyou'),
    url(r'^workshops_info/$', TemplateView.as_view(
        template_name='workshops_info.html',),
        name='workshops_info'),
    url(r'^workshops_upcoming/$',
        upcoming_workshops, name="upcoming_workshops"),
    url(r'^faq/$', TemplateView.as_view(template_name='faq.html',),
        name='faq'),
    url(r'^organisation/',
        include('wye.organisations.urls', namespace="organisations")),
    url(r'^workshop/',
        include('wye.workshops.urls', namespace="workshops")),
    url(r'^profile/',
        include('wye.profiles.urls', namespace="profiles")),
    url(r'^region/',
        include('wye.regions.urls', namespace="regions")),
    url(r'^reports/',
        include('wye.reports.urls', namespace="reports")),
    url(r'^invitation/(?P<user_id>[0-9]+)-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
        view=activate_view, name="invitation_register"),
    url(r'^$', HomePageView.as_view(),
        name='home-page'),
] + static(
    settings.STATIC_URL,
    document_root=settings.STATICFILES_DIRS) + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

wye/reports/models.py
# from django.db import models

# Create your models here.

wye/workshops/models.py
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django.core.validators import MaxValueValidator
# from django.core.urlresolvers import reverse_lazy
from django.db import models
from django.template import loader

from wye.base.constants import (
    FeedbackType,
    WorkshopLevel,
    WorkshopStatus,
    YesNO,
    WorkshopAudience
)
from wye.base.emailer_html import send_email_to_id
from wye.base.models import TimeAuditModel
from wye.organisations.models import Organisation
# from wye.regions.models import Location

# from .decorators import  validate_assignme_action


class WorkshopSections(TimeAuditModel):
    '''
    python2, Python3, Django, Flask, Gaming
    '''
    name = models.CharField(max_length=300, unique=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        db_table = 'workshop_section'

    def __str__(self):
        return '{}'.format(self.name)


class Workshop(TimeAuditModel):
    no_of_participants = models.PositiveIntegerField(
        validators=[MaxValueValidator(1000)])
    expected_date = models.DateField()
    description = models.TextField()
    requester = models.ForeignKey(
        Organisation, related_name='workshop_requester')
    presenter = models.ManyToManyField(User, related_name='workshop_presenter')
    # location = models.ForeignKey(Location, related_name='workshop_location')
    workshop_level = models.PositiveSmallIntegerField(
        choices=WorkshopLevel.CHOICES, verbose_name="Workshop Level")
    workshop_section = models.ForeignKey(WorkshopSections)
    number_of_volunteers = models.PositiveSmallIntegerField(
        default=0, null=True, blank=True)
    volunteer = models.ManyToManyField(User, related_name='workshop_volunteer')
    is_active = models.BooleanField(default=True)
    status = models.PositiveSmallIntegerField(
        choices=WorkshopStatus.CHOICES, verbose_name="Current Status",
        default=WorkshopStatus.REQUESTED)
    travel_reimbursement = models.PositiveSmallIntegerField(
        choices=YesNO.CHOICES,
        verbose_name="Travel Reimbursement Support",
        default=YesNO.NO)
    hotel_reimbursement = models.PositiveSmallIntegerField(
        choices=YesNO.CHOICES,
        verbose_name="Stay Reimbursement Support",
        default=YesNO.NO)
    budget = models.CharField(max_length=5, null=True)
    reimbursement_mode = models.TextField(null=True)
    tutor_reimbursement_flag = models.PositiveSmallIntegerField(
        choices=YesNO.CHOICES,
        verbose_name=" Do you need Travel/Stay reimbursement ?",
        default=YesNO.NO)
    comments = models.TextField()
    target_audience = models.PositiveSmallIntegerField(
        choices=WorkshopAudience.CHOICES, verbose_name="Audience",
        default=WorkshopAudience.BE_FINAL_YEAR)

    class Meta:
        db_table = 'workshops'

    def __str__(self):
        return '{}-{}'.format(self.requester, self.workshop_section)

    def save(self, force_insert=False, force_update=False, using=None):
        """
        send mail to region interested member whenever new workshop
        is requested in respective region, therefore overriding
        pre save method so mails are only send when new object
        is created.
        :param force_insert: bool force_insert
        :param force_update: bool force_insert
        :param using: using
        :return: instance
        """
        from wye.profiles.models import Profile
        if not self.id:
            domain = Site.objects.get_current().domain
            # get region_interested_member email ids to notify them
            region_interested_member = Profile.objects.filter(
                interested_locations=self.requester.location,
                usertype__slug='tutor'
            ).values_list('user__email', flat=True)

            if self and self.id:
                context = {
                    'workshop': self,
                    'date': self.expected_date,
                    'workshop_url': domain + '/workshop/{}/'.format(self.id),
                    'workshop_topic': self.workshop_section.name
                }
                subject = '[PythonExpress] Workshop request status.'
                email_body = loader.get_template(
                        'email_messages/workshop/create_workshop/message.html').render(
                        context)
                text_body = loader.get_template(
                        'email_messages/workshop/create_workshop/message.txt').render(
                        context)
                for email_id in region_interested_member:
                    send_email_to_id(
                        subject,
                        body=email_body,
                        email_id=email_id, text_body=text_body)

        super(Workshop, self).save(force_insert, force_update, using)

    def is_presenter(self, user):
        return self.presenter.filter(pk=user.pk).exists()

    def is_organiser(self, user):
        return self.requester.user.filter(pk=user.pk).exists()

    def manage_action(self, user, **kwargs):
        actions = {
            'accept': ("opt-in", self.assign_me),
            'reject': ("opt-out", self.assign_me),
            'decline': (WorkshopStatus.REQUESTED, self.set_status),
            'publish': (WorkshopStatus.REQUESTED, self.set_status),
            'hold': (WorkshopStatus.HOLD, self.set_status),
            'assign': "",
            'opt-in-as-volunteer': '',
            'opt-out-as-volunteer': ''
        }
        if kwargs.get('action') not in actions:
            return {
                'status': False,
                'msg': 'Action not allowed'
            }

        action, func = actions.get(kwargs.get('action'))
        kwargs["action"] = action
        return func(user, **kwargs)

    def set_status(self, user, **kwargs):
        self.status = kwargs.get('action')
        presenter_list = self.presenter.all()
        for u in presenter_list:
            self.presenter.remove(u)
        if kwargs.get('action') == WorkshopStatus.DECLINED:
            self.is_active = False
        else:
            self.is_active = True
        self.save()
        return {
            'status': True,
            'msg': 'Workshop successfully updated.'}

    # @validate_action_param(WorkshopAction.ACTIVE)
    def toggle_active(self, user, **kwargs):
        """
        Helper method to toggle is_active for the model.
        """

        action_map = {'active': True, 'deactive': False}
        action = kwargs.get('action')
        self.is_active = action_map.get(action)
        self.save()
        return {
            'status': True,
            'msg': 'Workshop successfully updated.'}

    # @validate_action_param(WorkshopAction.ASSIGNME)
    # @validate_assignme_action
    def assign_me(self, user, **kwargs):
        """
        Method to assign workshop by presenter self.
        """

        action_map = {
            'opt-in': self.presenter.add,
            'opt-out': self.presenter.remove
        }
        message_map = {
            'opt-in': 'Assigned successfully.',
            'opt-out': 'Unassigned successfully.'
        }
        assigned = {
            'opt-in': True,
            'opt-out': False
        }
        action = kwargs.get('action')
        if assigned[action] and self.presenter.filter(pk=user.pk).exists():
            # This save has been added as fail safe
            # once the logic is consolidated may be
            # it can be removed
            self.status = WorkshopStatus.ACCEPTED
            self.save()
            return {
                'status': False,
                'msg': 'Workshop has already been assigned.'
            }

        func = action_map.get(action)
        func(user)

        if action == 'opt-out':
            self.number_of_volunteers = 0
            self.volunteer.clear()

        if self.presenter.count() > 0:
            self.status = WorkshopStatus.ACCEPTED
        else:
            self.status = WorkshopStatus.REQUESTED
        self.save()

        return {
            'status': True,
            'assigned': assigned[action],
            'msg': message_map[action],
            'notify': True
        }

    def get_presenter_list(self):
        return [user.get_full_name() for user in self.presenter.all()]

    def get_tweet(self, context):
        workshop = self
        try:
            date = workshop.expected_date.strftime('%d-%m-%Y')
        except:
            date = workshop.expected_date

        topic = workshop.workshop_section
        organization = workshop.requester
        location = workshop.requester.location
        workshop_url = context.get('workshop_url', None)
        message = "{} workshop at {} on {} confirmed! Details: {}".format(
            topic, organization, date, workshop_url)
        if len(message) >= 140:
            message = "{} workshop at {} on {} confirmed! Details: {}".format(
                topic, location, date, workshop_url)
        if len(message) >= 140:
            message = "{} workshop on {} confirmed! Details :{}".format(
                topic, date, workshop_url)

        return message

        def opt_in_as_volunteer(self):
            pass

        def opt_out_as_volunteer(self):
            pass


class WorkshopRatingValues(TimeAuditModel):
    '''
    Requesting Rating values -2, -1, 0 , 1, 2
    '''

    name = models.CharField(max_length=300)
    feedback_type = models.PositiveSmallIntegerField(
        choices=FeedbackType.CHOICES, verbose_name="User_type")
    is_active = models.BooleanField(default=True)

    class Meta:
        db_table = 'workshop_vote_value'

    def __str__(self):
        return '{}-{}'.format(self.id, self.feedback_type)

    @classmethod
    def get_questions(cls, feedback_type):
        if feedback_type:
            print(cls.objects.filter(feedback_type=feedback_type))

            return cls.objects.filter(feedback_type=feedback_type)
        return None

wye/organisations/forms.py
from django import forms

# import autocomplete_light

from .models import Organisation, User


class OrganisationForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(OrganisationForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Organisation
        exclude = ('user', 'created_at', 'modified_at',
                   'active', 'created_by', 'modified_by')
#         widgets = {
#             'name': autocomplete_light.TextWidget('OrganisationAutocomplete'),
#         }


class OrganisationMemberAddForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(OrganisationMemberAddForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Organisation
        exclude = ('user', 'created_at', 'modified_at',
                   'name', 'organisation_type', 'description',
                   'location', 'organisation_role',
                   'active', 'created_by', 'modified_by')

    existing_user = forms.ModelChoiceField(queryset=User.objects.all(), required=False)
    new_user = forms.EmailField(label='Invite New User', required=False)


class UserRegistrationForm(forms.ModelForm):
    """
    Form class for completing a user's registration and activating the
    User.

    The class operates on a user model which is assumed to have the required
    fields of a BaseUserModel
    """
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    password = forms.CharField(max_length=30, widget=forms.PasswordInput)
    password_confirm = forms.CharField(max_length=30,
                                       widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        self.initial['username'] = ''

    class Meta:
        model = User
        exclude = ('is_staff', 'is_superuser', 'is_active', 'last_login',
                   'date_joined', 'groups', 'user_permissions')

wye/base/views.py
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect
from wye.organisations.models import Organisation
from wye.profiles.models import Profile
from wye.workshops.models import Workshop

from .constants import WorkshopStatus


class HomePageView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        organisationObj = Organisation.objects.filter(active=True)
        workshopObj = Workshop.objects.filter(is_active=True)
        context['organisation_registered_count'] = organisationObj.count()
        context['completed_workshop_count'] = workshopObj.filter(
            status=WorkshopStatus.COMPLETED).count()
        workshopObj = workshopObj.filter(status__in=[
            WorkshopStatus.REQUESTED,
            WorkshopStatus.ACCEPTED,
            WorkshopStatus.DECLINED])
        workshop_list = Workshop.objects.filter(
            is_active=True
        ).filter(
            status__in=[WorkshopStatus.REQUESTED, WorkshopStatus.ACCEPTED]
        ).order_by('expected_date')
        context['requested_workshop_count'] = workshopObj.count()
        context['tutor_registered_count'] = Profile.objects.filter(
            usertype__slug="tutor").count()
        context['upcoming_workshops'] = workshop_list
        return context


def verify_user_profile(f):
    '''
    This decorator check  whether the user are valid for certain views
    '''
    def wrap(request, *args, **kwargs):
        user_profile, created = Profile.objects.get_or_create(
            user__id=request.user.id)
        if not user_profile.is_profile_filled:
            return HttpResponseRedirect(
                '/profile/{}/edit'.format(request.user.username))
        return f(request, *args, **kwargs)
    return wrap

wye/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
    {% load static from staticfiles %}
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{% block title %}{{ SITE_INFO.site_name }}{% endblock %}</title>
        <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
        <link rel="stylesheet" href="{% static 'css/libs/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/app.css' %}">
        <link href='//fonts.googleapis.com/css?family=Open+Sans:300,400,600|Alegreya+Sans:800' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
        {% block extracss %} {% endblock %}
    </head>
    <body>
        <div class="wrapper">
            <nav class="navbar space-0-bottom navbar-default fill-white" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <i class="fa fa-bars"></i>
                        </button>
                        <a class="navbar-brand" href="/"><img id="logo" src="{% static 'img/logo_python_express.png' %}" width="80" alt="{{ SITE_INFO.site_name }}"></a>
                    </div>
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            {% if user.is_authenticated %}
                                <li><a href="/organisation/" class="{% if request.resolver_match.namespace == 'organisations' %}active{% endif %}">Organisations</a></li>
                                <li><a href="/workshop/" class="{% if request.resolver_match.namespace == 'workshops' %}active{% endif %}">Workshops</a></li>
                                {% if user.is_staff %}
                                	<li><a href="/region/" class="{% if request.resolver_match.namespace == 'regions' %}active{% endif %}">Regions</a></li>
                                {% endif %}
                            {% endif %}
                            <li><a href="/about" class="{% if request.resolver_match.url_name == 'about' %}active{% endif %}">About</a></li>
                                <!-- <li><a href="/workshops_upcoming" class="{% if request.resolver_match.url_name == 'upcoming_workshops' %}active{% endif %}">Upcoming Workshops</a></li> -->
                            
                            <li><a href="/faq" class="{% if request.resolver_match.url_name == 'faq' %}active{% endif %}">FAQ</a></li>
                            <li><a href="/supporter" class="{% if request.resolver_match.url_name == 'supporter' %}active{% endif %}">Partner</a></li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            {% block loginindicator %}
                                {% if user.is_authenticated %}
                                    <li>
                                    </li>
                                    <li class="dropdown">
                                       <a href="#" class="user-dropdown dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                            <img class="img-circle user_image" src="/media/{{user.profile.picture}}" /><span class="pad-3q">{{request.user.get_full_name}}</span><i class="fa fa-caret-down"></i>
                                        </a>
                                        <ul class="dropdown-menu sub" aria-labelledby="user_dropdown">
                                            <li><a href="/dashboard/" class="{% if request.resolver_match.namespace == 'dashboard' %}active{% endif %}"><i class="fa fa-dashboard fa-width"></i>Dashboard</a></li>
                                            <li><a href="{% url 'profiles:profile-page' slug=user.username %}"><i class="fa fa-user fa-width"></i>Profile</a></li>
                                            {% if user.is_staff %}
                                                <li><a href="{% url 'admin:index' %}" target="_blank">Admin</a></li>
                                            {% endif %}
                                            {% if user.is_staff %}
                                                <li><a href="{% url 'reports:home' %}" target="_blank">Reports</a></li>
                                            {% endif %}
                                            <li><a href="{% url 'account_logout' %}"><i class="fa fa-power-off fa-width"></i>Logout</a></li>
                                        </ul>
                                    </li>
                                {% else %}
                                <li><a href="{% url 'account_login' %}">Log In</a>
                                <li><a href="{% url 'account_signup' %}" class="nav-btn">Sign Up</a></li>
                                {% endif %}
                            {%endblock loginindicator %}
                        </ul>
                    </div>
                </div>
            </nav>
            {% block content_wrapper %}
                <header role="banner">
                    {% block header %}{% endblock %}
                </header>
                {% block sub_header %}{% endblock %}

                {% block content_full %}{% endblock %}

                {% block container_body %}
                    <div class="container push-2-top">
                        {% block content_body %}
                            {% block content %}
                            {% endblock %}
                        {% endblock %}
                    </div>
                {% endblock %}
            {% endblock %}
        </div>

        <footer class="push-3-top push-4-bottom block">
            <div class="container">
            {% block footer %}
                <div class="row">
                    <div class="col-sm-6 col-sm-offset-0 col-sm-push-6 col-xs-8 col-xs-offset-2">
                        <div class="row">
                            <div class="col-sm-6">
                                <ul class="list-silent">
                                    <li>
                                        <a href="/about" class="{% if request.resolver_match.url_name == 'about' %}active{% endif %}">About</a>
                                    </li>
                                    <li>
                                        <a href="/workshops_info" class="{% if request.resolver_match.url_name == 'workshops_info' %}active{% endif %}">Workshops Info</a>
                                    </li>
                                    <li>
                                        <a href="/contact" class="{% if request.resolver_match.url_name == 'contact' %}active{% endif %}">Contact Us</a>
                                    </li>
                                    <li>
                                        <a target="_blank" href="http://blog.pythonexpress.in/">Blog</a>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-sm-6">
                                <ul class="social list-silent">
                                    {% for link in SITE_INFO.footer.social %}
                                        <li class="social__link">
                                            <a target="_blank" href="{{ link.url }}" class="social__media">
                                                <i class="{{ link.icon }} social__icon social__icon--{{ link.media }}"></i>
                                                <span class="social__label">{{ link.label }}</span>
                                            </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-sm-offset-0 col-sm-pull-6 col-xs-8 col-xs-offset-2">
                        <div class="copyright">
                            <div class="copyright__logo space-1-top">
                                <img class="contain-width" src="{% static 'img/logo_python_express_monochrome.png' %}" alt="">
                            </div>
                            <div class="copyright__label space-1-top">
                                &copy;&nbsp;{{ SITE_INFO.footer.copyright.year }}&nbsp;
                                <a href="{{ SITE_INFO.footer.copyright.url }}">{{ SITE_INFO.footer.copyright.label }}</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endblock %}
            </div>
        </footer>
        <script src="{% static 'js/libs/jquery-2.1.4.min.js' %}"></script>
        <script src="{% static 'js/libs/bootstrap.min.js' %}"></script>
        <script src="{% static 'lead_create_form.js' %}"></script>
        {% block footer_scripts %}{% endblock %}
    </body>
</html>

wye/templates/contact.html
{% extends "base.html" %}

{% block header %}
    <div class="banner push-2 text-center">
        <h1 class="space-0">{% if form %}Contact Us{% else %}Thank You {% endif %}</h1>
    </div>
{% endblock %}

{% block content %}
    <div class="push-6-bottom">
        <div class="row">
            <div class="col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2">
                {% if form %}
                <form method="post" action="">
                    {% csrf_token %}
                    {{form.as_p}}
                    <input type="submit" class="btn btn-theme regular" value="Create">
                </form>
                {% else %}
                    Your response has been recorded. We will get in touch with you shortly.
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

wye/templates/upcoming.html
{% extends "base.html" %}
{% block title %}Workshops | {{ block.super }}{% endblock %}

{% block header %}
    <div class="banner push-2 text-center">
        <h1 class="space-0">Upcoming Workshops</h1>
    </div>
{% endblock %}
{% block extracss %}

<!--<link href="https://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" />-->
<link href="https://cdn.datatables.net/plug-ins/1.10.7/integration/bootstrap/3/dataTables.bootstrap.css" rel="stylesheet" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/plug-ins/1.10.7/integration/bootstrap/3/dataTables.bootstrap.js"></script>
{% endblock %}

{% block content %}
    <div class="push-1-top push-4-bottom">
        <div class="alert alert-warning">
            <h4>Note:</h4>
            <ul class="pad-1">
                <li>The dates displayed are tentative. It can be changed as per the tutors' availability and convenience.
                <a href="https://pythonexpress.in/contact/">Contact us.</a>
                </li>
                <li>Changes in dates will be discussed via email between both the tutor and college.</li>
                <li>If required, we will work with the college to help share logistics cost.</li>
            </ul>
        </div>
        {% if workshop_list %}
            <div class="table-responsive">
                <table id="upcoming" class="table table-striped table-bordered space-3-top" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>sl.no </th>
                            <th>Location</th>
                            <th>Workshop Section</th>
                            <th>Workshop level</th>
                            <th>Tentative Dates *</th>
                            <th>College</th>
                            <th>presenter</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for workshop in workshop_list %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td><u><a href="/workshop/{{workshop.id}}/">{{workshop.location}}</a></u></td>
                                <td>{{workshop.workshop_section.name}}</td>
                                <td>{{workshop.get_workshop_level_display}}</td>

                                <td>{{workshop.expected_date|date:'l,  M. d Y' }}</td>
                                <td>{{workshop.requester.name}}</td>
                                <td>
                                    {% for u in  workshop.presenter.all %}
                                        {{u.get_full_name}}
                                    {% endfor %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        {% else %}
        <h3>All workshop request are completed</h3>
        {% endif %}
    </div>
{% endblock %}

{% block footer_scripts %}
    <script>
        $('#upcoming').dataTable({
            "iDisplayLength": 50
        } );
    </script>
{% endblock %}